version: '3.3'

networks:
  message-network:
    driver: bridge

volumes:
  message-mysql-volume:

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "ratelimit"
    ports:
      - "3306:3306"
    networks:
      - message-network
    volumes:
      - message-mysql-volume:/var/lib/mysql
